---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-helloworld
  name: docker-helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-helloworld
  template:
    metadata:
      labels:
        app: docker-helloworld
    spec:
      containers:
        - name: docker-helloworld
          image: public.ecr.aws/e5k2g5i2/e-plansoftdemoimg
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
              name: http
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/apache2/apache2.conf
              subPath: apache2.conf
            - name: crt
              mountPath: /etc/pki/tls/certs/localhost.crt
              subPath: rootCA.crt
            - name: key
              mountPath: /etc/pki/tls/certs/localhost.key
              subPath: rootCA.key
      volumes:
        - name: config
          configMap:
            name: apache-config
            items:
              - key: apache2.conf
                path: apache2.conf
        - name: crt
          configMap:
            name: apache-config
            items:
              - key: rootCA.crt
                path: rootCA.crt
        - name: key
          configMap:
            name: apache-config
            items:
              - key: rootCA.key
                path: rootCA.key
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-helloworld
    k8s-app: docker-helloworld
  name: docker-helloworld
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8085
  type: LoadBalancer
  selector:
    app: docker-helloworld
