---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-helloworld
  name: docker-helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-helloworld
  template:
    metadata:
      labels:
        app: docker-helloworld
    spec:
      containers:
        - name: docker-helloworld
          image: ubuntu/apache2
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
              name: http
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/apache2/apache2.conf
              subPath: apache2.conf
      volumes:
        - name: config
          configMap:
            name: apache-config
            items:
              - key: apache2.conf
                path: apache2.conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-helloworld
    k8s-app: docker-helloworld
  name: docker-helloworld
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8085
  type: LoadBalancer
  selector:
    app: docker-helloworld
